### ISSUE TITLE
Change namespace Blazor.LoadingIndicator 

### ISSUE THREAD

**Issue by WizX20** [h3x4d3c1m4l/BlazorProgressIndicator#7]
You are starting with the namespace Blazor.* which is already a namespace in the Blazor framework. Consider changing this since it can cause conflicts.

**Comment by h3x4d3c1m4l** [comment]
Hi,

Thanks for your suggestion. I'm not sure how this could actually cause a conflict. Can you explain a bit more on this?

**Comment by WizX20** [comment]
I thought about it, and I'm closing it. I no longer see the issue. Maybe when Blazor would introduce a similar namespace it would be inconvenient at most. But easy to fix with an namespace alias for example.

**Comment by h3x4d3c1m4l** [comment]
Reopening, I decided to change the name of the library to H3x.BlazorProgressIndicator.
This will become the namespace of the lib, as well as the NuGet package name, and will resolve this issue too.
